# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: true
    files:
      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - { label: "Body", name: "body", widget: "markdown" }
